version: '3.3'
services:
  database: 
    image: mysql
    volume:
      - datastore:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: devopsblog
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    networks:
      - backend
  
  wordpress:
    depends_on: 
      - database
    image: wordpress
    ports:
      - 6000:80
    restart: always
    environment: 
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: devops 
      WORDPRESS_DB_PASSWORD: devops
      WORDPRESS_DB_NAME: devopsblog
      WORDPRESS_TABLE_PREFIX: pragra
    networks: 
      - backend
      - frontend
  
  phpmyadmin:
      depends_on: 
      - database
    image: phpmyadmin
    ports:
      - 7000:80
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
      PMA_HOST: database:3306
    networks: 
      - backend
      - frontend
  
  volumes: 
    datastore: {}
  
  networks: 
    frontend:
    backend:

